### ISSUE TITLE
how to label data

### ISSUE THREAD

**Issue by liuming9157** [beiyuouo/hcaptcha-model-factory#3]
In wiki, it shows as follows:
I think you do not need a label tool for this task... Just drag to the corresponding label folder is enough. It's easy, right?

I think it's hard to understand.Can you explain how to label data in detail?

**Comment by beiyuouo** [comment]
You just need to open two folders and drag and drop pictures to categorize them...

**Comment by liuming9157** [comment]
Thanks. I saw your updation in the wiki. Appreciation!!!

**Comment by beiyuouo** [comment]
Cool!
