### ISSUE TITLE
add a new photo extension

### ISSUE THREAD

**Issue by ninjadoc107** [beiyuouo/hcaptcha-model-factory#37]
most of the photos being downloaded by hcaptcha, are coming in jfif, you could add this extension in your project

**Comment by ninjadoc107** [comment]
> ah? what do you mean

the project only reads jpeg, png, webp etc files

**Comment by QIN2DIM** [comment]
https://github.com/beiyuouo/hcaptcha-model-factory/blob/36f607c7213e8a7c2e7de453733754beecced60b/src/components/utils/toolbox/toolbox.py#L11

**Comment by ninjadoc107** [comment]
> 

how do you make the models, do you download the images manually and just separate them in hcaptcha-model-factory?

**Comment by QIN2DIM** [comment]
You can search how to build image dataset 😳or read the repo wiki for more details.

**Comment by ninjadoc107** [comment]
> .

yes, I was getting the new hcaptcha images from the console and separating them into the hcaptcha model factory files
