### ISSUE TITLE
Creating model

### ISSUE THREAD

**Issue by Oberonskii** [beiyuouo/hcaptcha-model-factory#4]
Hello.
I do not exacly understand how this works.
If I would like to create a model for trucks for example, would I do this?
Put images that contain trucks in the "yes" folder and images that dont have trucks in the "bad" folder
Then run run.bat and wait.
Would this be correct?
Thanks!

**Comment by beiyuouo** [comment]
Yes, you are right. You can get more useful information in [wiki](https://github.com/beiyuouo/hcaptcha-model-factory/wiki)

**Comment by Oberonskii** [comment]
Thanks. I've already read the wiki but my ennglish isn't the best.
Will I have to get the images for training by hand or are there any other methods of scraping them?
Also, how can I train a model? When running the main.py files with the flags --mode train, I get the error
FileNotFoundError: Found no valid file for the classes 0, 1. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp
Thank you

**Comment by Oberonskii** [comment]
I just put 20 images in the yes directory and 26 in the bad. When running run.bat, it tells me "9 images" all the time. Shouldn't that be at least 20?

**Comment by beiyuouo** [comment]
You can scrap them using [hcaptcha-challenger](https://github.com/QIN2DIM/hcaptcha-challenger).
If you train from scratch, You need to create the `origin` folder with `yes` and `bad` in it(note: do not have any subfolder in `yes` and `no`). Then you need to modify the `task_name` in `config.py`. After that you can do the same as `run.bat`.

**Comment by Oberonskii** [comment]
Okey thanks. But how can I scrape them using that repo? Isn‘t it just a solver?

**Comment by beiyuouo** [comment]
Yes, it's a solver. But the solver also need to get the image first haha. You need to modify some code to achieve that.
