### ISSUE TITLE
[feat]

### ISSUE THREAD

**Issue by ninjadoc107** [beiyuouo/hcaptcha-model-factory#41]
you can put jfif extension in your old project, the one you manually separated as photos in yes/bad, a lot of it, it's very easy to use.

**Comment by ninjadoc107** [comment]
> you can put jfif extension in your old project, the one you manually separated as photos in yes/bad, a lot of it, it's very easy to use.


![image](https://user-images.githubusercontent.com/110185860/194772629-2988657d-c2fd-418a-ac8c-7d8a0b040cfe.png)

and also because it is an old version, it is already very well tested, the new one always returns a different error..

**Comment by beiyuouo** [comment]
I won't maintain the old version anymore, you can do it by yourself, it's easy. You only have one image, so why you need to auto label? You can skip this step.

**Comment by ninjadoc107** [comment]
> Não vou mais manter a versão antiga, você pode fazer isso sozinho, é fácil. Você só tem uma imagem, então por que você precisa rotular automaticamente? Você pode pular esta etapa.

hey, I tried to add a jfif extension here in the old version but I couldn't

**Comment by beiyuouo** [comment]
Okay, if you cannot, you can use the latest version.

**Comment by ninjadoc107** [comment]
> Ok, se você não puder, pode usar a versão mais recente.

I'm not able to use the latest version, but ok, I'll try to update the old one here :v

**Comment by ninjadoc107** [comment]
> Okay, if you cannot, you can use the latest version.

do you think by the latest version i can update the old version?

**Comment by beiyuouo** [comment]
I don't know. Enjoy coding haha

**Comment by ninjadoc107** [comment]
> I don't know. Enjoy coding haha

and I still got a hcaptcha collector, I did once the images can be separated by the hcaptcha name that I don't need to put, are you happy?

**Comment by beiyuouo** [comment]
Sorry, I can’t understand what you are talking about.

**Comment by QIN2DIM** [comment]
@ninjadoc107 如果你不會説英文，可以把机翻输出设置为中文
