### ISSUE TITLE
[Feature] Validation Mode for ONNX Model

### ISSUE THREAD

**Issue by Vinyzu** [beiyuouo/hcaptcha-model-factory#7]
Yo, it would be cool to validate/check the accuracy of onnx files/models.
would this be possible?

**Comment by Vinyzu** [comment]
Update: i think its cv2_validate.py, but the code didnt work really well so i coded my own.

**Comment by beiyuouo** [comment]
usually I use PTH model to validate and then convert it to onnx, haha. Welcome to pull request~!
