### ISSUE TITLE
adding on to model

### ISSUE THREAD

**Issue by dontbanmeplz** [beiyuouo/hcaptcha-model-factory#8]
I have a few questions i am decent at python but do not have much experience with ai.

1. How can i train a new model? I see the instructions but it is very hard to understand

2. How do i add on to the model in hcaptcha-challenger? I want to fix the model they have.

3. How can i test it? So i know how to use it

**Comment by beiyuouo** [comment]
Hi @dontbanmeplz, you can see the usage in [wiki](https://github.com/beiyuouo/hcaptcha-model-factory/wiki). Sorry for my English, if anything you cannot understand, you are welcome to give your suggestion.

Answer:
1. install requirements, label data, change task_name in `config.py`, run the command `python main.py --split --mode trainval`
2. You only need to modify the `object.yaml` in `hcaptcha-challenger`. For contributing to `hcaptcha-challenger`, you can upload your onnx model to [gofile](https://gofile.io/) and open a pull request to  modify `object.yaml` with model accuracy and the number of pictures collected.
3. See in [wiki](https://github.com/beiyuouo/hcaptcha-model-factory/wiki). `python main.py --mode val`

**Comment by ninjadoc107** [comment]
> Oi@dontbanmeplz, você pode ver o uso no [wiki](https://github.com/beiyuouo/hcaptcha-model-factory/wiki) . Desculpe pelo meu inglês, se houver algo que você não consiga entender, fique à vontade para dar sua sugestão.
> 
> Responda:
> 
> 1. instalar requisitos, rotular dados, alterar task_name em `config.py`, executar o comando`python main.py --split --mode trainval`
> 2. Você só precisa modificar o `object.yaml`arquivo `hcaptcha-challenger`. Para contribuir com o `hcaptcha-challenger`, você pode fazer o upload do seu modelo onnx para [gofile](https://gofile.io/) e abrir um pull request para modificar `object.yaml`com a precisão do modelo e o número de fotos coletadas.
> 3. Veja em [wiki](https://github.com/beiyuouo/hcaptcha-model-factory/wiki) .`python main.py --mode val`

but where do I put the new photos that he will train, I still don't understand very well

**Comment by beiyuouo** [comment]
See here.

![image](https://user-images.githubusercontent.com/44976445/187008978-90984924-2236-46de-a08d-ba1555af6e85.png)

**Comment by ninjadoc107** [comment]
> Veja aqui.
> 
> ![imagem](https://user-images.githubusercontent.com/44976445/187008978-90984924-2236-46de-a08d-ba1555af6e85.png)

in [task] do I put the name of the correct challenge?

**Comment by beiyuouo** [comment]
No, you can use whatever you want.

**Comment by ninjadoc107** [comment]
> Não, você pode usar o que quiser.

and where will he get the images and train the model?

**Comment by beiyuouo** [comment]
No, this repo is just a model factory for training and evaluting the model. You can use [`hcaptcha-challenger`](https://github.com/QIN2DIM/hcaptcha-challenger) to collect the images.

**Comment by beiyuouo** [comment]
I can't get you.

**Comment by dontbanmeplz** [comment]
> I can't get it. I have explained above how to place the pictures, how to divide data into train set and val set, and how to start the training.

You should make a video on how to do it, I'm sure it would clear up any problems @beiyuouo

**Comment by beiyuouo** [comment]
> > I can't get it. I have explained above how to place the pictures, how to divide data into train set and val set, and how to start the training.
> 
> You should make a video on how to do it, I'm sure it would clear up any problems @beiyuouo

Okay, I’ll finished the project structure in wiki. I think we don’t need any video. All you have to do is put the images in the right place and run the command.

**Comment by dontbanmeplz** [comment]
> > > I can't get it. I have explained above how to place the pictures, how to divide data into train set and val set, and how to start the training.
> > 
> > 
> > You should make a video on how to do it, I'm sure it would clear up any problems @beiyuouo
> 
> Okay, I’ll finished the project structure in wiki. I think we don’t need any video. All you have to do is put the images in the right place and run the command.

ok thank you for the updated tutorial, but how can i make a new model for a challenge like, "click all boxes with a horse" what would i do for the "bad" image folder @beiyuouo

**Comment by beiyuouo** [comment]
@dontbanmeplz, Please check here. https://github.com/beiyuouo/hcaptcha-model-factory/wiki#full-workflow-to-add-a-new-challenge

**Comment by dontbanmeplz** [comment]
@beiyuouo what would be in the bad folder in this situation?

**Comment by beiyuouo** [comment]
Images you don't click. Which not contain a horse.
